/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tbcPost_Radio
	DROP CONSTRAINT PK_NodeRadio
GO
ALTER TABLE dbo.tbcPost_Radio ADD CONSTRAINT
	PK_NodeRadio PRIMARY KEY CLUSTERED 
	(
	PostID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.tbcPost_Radio
	DROP COLUMN PostRadioID
GO
ALTER TABLE dbo.tbcPost_Radio SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tbcPost_SiteBanner
	DROP CONSTRAINT PK_NodeSiteBanner
GO
ALTER TABLE dbo.tbcPost_SiteBanner ADD CONSTRAINT
	PK_NodeSiteBanner PRIMARY KEY CLUSTERED 
	(
	PostID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.tbcPost_SiteBanner
	DROP COLUMN PostSiteBannerID
GO
ALTER TABLE dbo.tbcPost_SiteBanner SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
