/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.tbcFeedback
	(
	FeedbackID int NOT NULL IDENTITY (1, 1),
	DateCreated datetime NOT NULL,
	UserID int NOT NULL,
	Url varchar(100) NOT NULL,
	Comments varchar(MAX) NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.tbcFeedback ADD CONSTRAINT
	DF_tbcFeedback_DateCreated DEFAULT GETDATE() FOR DateCreated
GO
ALTER TABLE dbo.tbcFeedback ADD CONSTRAINT
	PK_tbcFeedback PRIMARY KEY CLUSTERED 
	(
	FeedbackID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.tbcFeedback SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
