CREATE TABLE dbo.tbcParentChild
(
	ParentChildID int IDENTITY(1,1) NOT NULL,
	ParentUserID int NOT NULL,
	ChildUserID int NOT NULL
) ON [PRIMARY]

ALTER TABLE dbo.tbcParentChild ADD CONSTRAINT PK_tbcParentChild PRIMARY KEY CLUSTERED 
(
	ParentChildID
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.tbcParentChild SET (LOCK_ESCALATION = TABLE)

ALTER TABLE dbo.tbcParentChild ADD CONSTRAINT IX_tbcParentChild__Parent__Child UNIQUE NONCLUSTERED 
(
	ParentUserID,
	ChildUserID
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]