CREATE TABLE dbo.tbcPost_Transaction
(
	PostID int NOT NULL,
	Amount money NOT NULL
)  ON [PRIMARY]

ALTER TABLE dbo.tbcPost_Transaction ADD CONSTRAINT PK_tbcPost_Transaction PRIMARY KEY CLUSTERED 
(
	PostID
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.tbcPost_Transaction SET (LOCK_ESCALATION = TABLE)
